### PR TITLE
Add basic setup, startup, and usage instructions

### PR DESCRIPTION
**Pull request by mschmele**
This just spells out a few of the things that I stupidly missed when following your README. I do not use `deps.edn`, but am more than happy to add those commands if you provide them so I know that they're correct.

Thank you for writing all of this down in the first place! It is immensely helpful.

### CODE REVIEW

**Comment by seancorfield** [comment]
Thanks. Some feedback:

In general, avoid "simple"/"easy"/"just" as some beginners find it condescending (if they're struggling, it's clearly not "simple" or "easy"). If you can take a first run are rewording the two paragraphs to remove that, I can wordsmith further after merging.

- "Launching and Usage" => "Portal: Launch and Usage"
- "your root configuration file" => "your user configuration file" (the "root" configuration is what is baked into the tool itself)

With those updates, I'll merge it in and add the `deps.edn` instructions.

**Comment by mschmele** [comment]
Ah fair point about "simple", etc - wouldn't have even thought about that! Updates incoming 🚧

**Comment by seancorfield** [comment]
Thank you!

**Comment by mschmele** [comment]
Of course! Makes more sense to have that documentation be available to help everybody rather than some internal team doc

**Pull request merged**
